version: "3.9"
services:
  discovery-server:
    image: discovery-server
    networks:
      - kf-shared-network
    ports:
      - "8761:8761"
    container_name: discovery-server

  config-server:
    image: config-server
    networks:
      - kf-shared-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/spring-boot-config/default" ]
      interval: 30s
      timeout: 10s
      retries: 5

    ports:
      - "8888:8888"
    depends_on:
      - discovery-server
    container_name: config-server

  loan-limit-calculator-service:
    image: loan-limit-calculator-service
    networks:
      - kf-shared-network
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
    container_name: loan-limit-calculator-service

  loan-limit-check-service:
    image: loan-limit-check-service
    networks:
      - kf-shared-network
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - discovery-server
    restart: always
    container_name: loan-limit-check-service

  credit-score-service:
    image: credit-score-service
    networks:
      - kf-shared-network
    ports:
      - "8084:8084"
    depends_on:
      - discovery-server
    container_name: credit-score-service

networks:
  kf-shared-network:
    name: kf-shared-network
    driver: bridge